#! /bin/sh
# /etc/init.d/noip

### BEGIN INIT INFO
# http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html
# Provides:          noip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting RaspHypCam"
    # run application you want to start
    sh /home/pi/Documents/RaspHypCam/autorun.sh
    ;;
  stop)
    echo "Stopping RaspHypCam"
    # kill application you want to stop
    killall RaspHypCam
    ;;
  *)
    echo "Usage: /etc/init.d/RaspHypCam {start|stop}"
    exit 1
    ;;
esac

exit 0 
